# Generated by Django 5.1.4 on 2025-02-08 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chargesaffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('refReservation', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('chargerAffaire', models.CharField(max_length=20)),
                ('dateReservation', models.DateField(auto_now=True)),
                ('client', models.CharField(max_length=50)),
                ('etat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('refMateriel', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('situation', models.CharField(max_length=50)),
                ('lieu', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetilsReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('qte', models.IntegerField(default=1)),
                ('dateLivraison', models.DateField(auto_now_add=True)),
                ('dateRetour', models.DateField()),
                ('refReservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='Modulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamme', models.CharField(choices=[('evenement', 'EVENEMENT'), ('chantier', 'CHANTIER')], max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('refMateriel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.stock')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeElectrogene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puissance', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('refMateriel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.stock')),
            ],
        ),
        migrations.CreateModel(
            name='CabinesAutonome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamme', models.CharField(choices=[('evenement', 'EVENEMENT'), ('chantier', 'CHANTIER')], max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('refMateriel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.stock')),
            ],
        ),
    ]
