# Generated by Django 5.1.4 on 2025-01-20 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chargesaffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('refReservation', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('chargerAffaire', models.CharField(max_length=20)),
                ('dateReservation', models.DateField(auto_now=True)),
                ('etat', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DetilsReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('qte', models.IntegerField()),
                ('dateLivraison', models.DateField()),
                ('dateRetour', models.DateField()),
                ('refReservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref', to='inventaire.reservation')),
            ],
        ),
    ]
