# Generated by Django 5.1.4 on 2025-01-20 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detilsreservation',
            name='refReservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.reservation'),
        ),
    ]
