# Generated by Django 4.2.3 on 2025-01-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_alter_detilsreservation_refreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('refMateriel', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('situation', models.CharField(choices=[('louer', 'LOUER'), ('disponible', 'DISPONIBLE'), ('vente', 'VENTE'), ('don', 'DON'), ('verifie', 'A VERIFIER'), ('utiliser', 'UTILISER')], max_length=50)),
                ('lieu', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('GE', 'GROUPE ELECTROGENE'), ('MODULAIRE', 'MOUDULAIRE'), ('CABINE', 'CABINE AUTONOME')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamme', models.CharField(choices=[('evenement', 'EVENEMENT'), ('chantier', 'CHANTIER')], max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('refMateriel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.stock')),
            ],
        ),
        migrations.CreateModel(
            name='GroupeElectrogene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puissance', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('refMateriel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.stock')),
            ],
        ),
        migrations.CreateModel(
            name='CabinesAutonome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamme', models.CharField(choices=[('evenement', 'EVENEMENT'), ('chantier', 'CHANTIER')], max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('refMateriel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaire.stock')),
            ],
        ),
    ]
