# Generated by Django 5.1.4 on 2025-01-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_stock_modulaire_groupeelectrogene_cabinesautonome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='etat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='categorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='situation',
            field=models.CharField(max_length=50),
        ),
    ]
