# Generated by Django 5.1.4 on 2025-02-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0004_alter_reservation_etat_alter_stock_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.CharField(default='client', max_length=50),
            preserve_default=False,
        ),
    ]
