# Generated by Django 5.1.4 on 2025-02-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_reservation_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='qte',
            field=models.IntegerField(default=1),
        ),
    ]
