# Generated by Django 5.1.4 on 2025-02-03 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0006_alter_detilsreservation_datelivraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='refReservation',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='format invalid', regex='^(1[0-2]|[1-9])/\\d{4}$')]),
        ),
    ]
