# Generated by Django 5.1.5 on 2025-03-08 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0007_alter_detilsreservation_datelivraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 15, 15, 25, 544322, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 15, 15, 25, 544335, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 15, 15, 25, 544026, tzinfo=datetime.timezone.utc)),
        ),
    ]
