# Generated by Django 5.1.4 on 2025-03-14 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0008_alter_detilsreservation_datelivraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(default=datetime.datetime(2025, 3, 14, 23, 17, 16, 625244, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2025, 3, 14, 23, 17, 16, 625244, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateField(default=datetime.datetime(2025, 3, 14, 23, 17, 16, 624429, tzinfo=datetime.timezone.utc)),
        ),
    ]
