# Generated by Django 5.1.4 on 2025-03-15 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0010_alter_detilsreservation_datelivraison_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeMovement', models.CharField(max_length=20)),
                ('dateMovement', models.DateField()),
                ('refMateriel', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=50)),
                ('qte', models.IntegerField()),
                ('matTrans', models.CharField(max_length=40, null=True)),
                ('condTrans', models.CharField(max_length=30, null=True)),
                ('observations', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 21, 51, 3, 734831, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 21, 51, 3, 734831, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 21, 51, 3, 734831, tzinfo=datetime.timezone.utc)),
        ),
    ]
