# Generated by Django 5.1.4 on 2025-03-15 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0012_movement_lieu_movement_typelocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='client',
            field=models.CharField(default=' ', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movement',
            name='depot',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 23, 23, 46, 293819, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 23, 23, 46, 293819, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 23, 23, 46, 293819, tzinfo=datetime.timezone.utc)),
        ),
    ]
