# Generated by Django 5.1.4 on 2025-03-28 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0013_movement_client_movement_depot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(default=datetime.datetime(2025, 3, 28, 22, 55, 15, 551104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2025, 3, 28, 22, 55, 15, 551104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateField(default=datetime.datetime(2025, 3, 28, 22, 55, 15, 551104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lieu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
