# Generated by Django 5.1.4 on 2025-03-29 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0014_alter_detilsreservation_datelivraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(default=datetime.datetime(2025, 3, 29, 16, 14, 19, 499641, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2025, 3, 29, 16, 14, 19, 499641, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateField(default=datetime.datetime(2025, 3, 29, 16, 14, 19, 498611, tzinfo=datetime.timezone.utc)),
        ),
    ]
