# Generated by Django 5.1.4 on 2025-04-23 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0015_stock_client_alter_detilsreservation_datelivraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_created=True,blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(default=datetime.datetime(2025, 4, 23, 21, 38, 16, 611542, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2025, 4, 23, 21, 38, 16, 611542, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateField(default=datetime.datetime(2025, 4, 23, 21, 38, 16, 611542, tzinfo=datetime.timezone.utc)),
        ),
    ]
