# Generated by Django 5.1.4 on 2025-04-23 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0016_stock_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateLivraison',
            field=models.DateField(default=datetime.datetime(2025, 4, 23, 21, 39, 29, 448514, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='detilsreservation',
            name='dateRetour',
            field=models.DateField(default=datetime.datetime(2025, 4, 23, 21, 39, 29, 448514, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='dateReservation',
            field=models.DateField(default=datetime.datetime(2025, 4, 23, 21, 39, 29, 448514, tzinfo=datetime.timezone.utc)),
        ),
    ]
