# Generated by Django 5.1.4 on 2025-03-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('bl', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=60)),
                ('dateLivraison', models.DateField()),
                ('refMateriel', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=50)),
                ('qte', models.IntegerField()),
                ('observations', models.CharField(max_length=200)),
                ('chargerAffaire', models.CharField(max_length=40)),
                ('typeLivraison', models.CharField(max_length=30)),
                ('chantier', models.CharField(max_length=50)),
                ('typeTrans', models.CharField(max_length=20)),
                ('matTrans', models.CharField(max_length=40)),
                ('condTrans', models.CharField(max_length=30)),
            ],
        ),
    ]
