# Generated by Django 5.1.4 on 2025-03-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livraison',
            name='bl',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
