# Generated by Django 5.1.4 on 2025-03-02 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0002_alter_livraison_bl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='qte',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='refMateriel',
        ),
        migrations.CreateModel(
            name='DetailsLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refMateriel', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=50)),
                ('qte', models.IntegerField()),
                ('observations', models.CharField(max_length=200)),
                ('bl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livraisons.livraison')),
            ],
        ),
    ]
