# Generated by Django 5.1.4 on 2025-03-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0003_remove_livraison_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailslivraison',
            name='observations',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='bl',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='condTrans',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='livraison',
            name='matTrans',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
