# Generated by Django 5.1.5 on 2025-03-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0004_alter_detailslivraison_observations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraison',
            name='condTrans',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='matTrans',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='typeLivraison',
        ),
        migrations.RemoveField(
            model_name='livraison',
            name='typeTrans',
        ),
        migrations.AddField(
            model_name='detailslivraison',
            name='condTrans',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='detailslivraison',
            name='matTrans',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='livraison',
            name='created_by',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
