# Generated by Django 5.1.4 on 2025-03-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0006_livraison_typelivraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeMovement', models.CharField(max_length=20)),
                ('dateMovement', models.DateField()),
                ('refMateriel', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=50)),
                ('qte', models.IntegerField()),
                ('matTrans', models.CharField(max_length=40, null=True)),
                ('condTrans', models.CharField(max_length=30, null=True)),
                ('observations', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
