# Generated by Django 5.1.4 on 2025-03-15 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0007_mouvement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mouvement',
            new_name='Movement',
        ),
    ]
