# Generated by Django 5.1.4 on 2025-03-15 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livraisons', '0008_rename_mouvement_movement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movement',
        ),
    ]
